# Generated by Django 4.2 on 2024-03-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='interface',
            field=models.CharField(choices=[], default='DEFAULT', max_length=255),
        ),
    ]
