# Generated by Django 4.2 on 2024-03-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=255),
        ),
        migrations.AddField(
            model_name='productstock',
            name='interface',
            field=models.CharField(choices=[], default='DEFAULT', max_length=255),
        ),
        migrations.AddField(
            model_name='productstock',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('unit', 'Unit')], default='unit', max_length=255),
        ),
    ]
