# Generated by Django 4.2 on 2024-03-26 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_test_super_element'),
        ('product', '0003_product_status_productstock_interface_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='profiles.profile'),
        ),
    ]
