# Generated by Django 4.2 on 2024-03-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='interface',
            field=models.CharField(choices=[('BUZZ:BUZZ', 'BUZZ:BUZZ')], default='DEFAULT', max_length=255),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='interface',
            field=models.CharField(choices=[('BUZZ:BUZZ', 'BUZZ:BUZZ')], default='DEFAULT', max_length=255),
        ),
    ]
